// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TomDroidSharp
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int firstNoteContent = 2130968576;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_compat_item = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_compat_item_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_compat_item_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_shadow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_small = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_small_toggle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_toggle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int drop_shadow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int drop_shadow_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int drop_shadow_separator = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int file = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int folder = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int highlight = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_launcher = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_sync = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_shortcut = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int mono = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int size = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int text = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tray_handle_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int triangle_selector = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int white_triangle = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int xml = 2130837527;
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030053
			public const int NewNoteBodyHint = 2130903123;
			
			// aapt resource value: 0x7f030051
			public const int NewNoteTitle = 2130903121;
			
			// aapt resource value: 0x7f030052
			public const int NewNoteTitleHint = 2130903122;
			
			// aapt resource value: 0x7f03003c
			public const int SearchResultTitle = 2130903100;
			
			// aapt resource value: 0x7f0300c7
			public const int about_translators = 2130903239;
			
			// aapt resource value: 0x7f030034
			public const int allNotebooksFilter = 2130903092;
			
			// aapt resource value: 0x7f030001
			public const int app_desc = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int author = 2130903042;
			
			// aapt resource value: 0x7f030084
			public const int autoBackupPref = 2130903172;
			
			// aapt resource value: 0x7f030083
			public const int autoBackupPrefTitle = 2130903171;
			
			// aapt resource value: 0x7f030057
			public const int back = 2130903127;
			
			// aapt resource value: 0x7f030082
			public const int backupPref = 2130903170;
			
			// aapt resource value: 0x7f030081
			public const int backupPrefTitle = 2130903169;
			
			// aapt resource value: 0x7f0300b4
			public const int backup_notes = 2130903220;
			
			// aapt resource value: 0x7f0300b3
			public const int backup_notes_title = 2130903219;
			
			// aapt resource value: 0x7f030058
			public const int bold = 2130903128;
			
			// aapt resource value: 0x7f03000d
			public const int btnCancel = 2130903053;
			
			// aapt resource value: 0x7f0300c1
			public const int btnCancelImport = 2130903233;
			
			// aapt resource value: 0x7f03000e
			public const int btnClose = 2130903054;
			
			// aapt resource value: 0x7f03000c
			public const int btnOk = 2130903052;
			
			// aapt resource value: 0x7f03000f
			public const int btnProjectPage = 2130903055;
			
			// aapt resource value: 0x7f030045
			public const int btnRemoveShortcut = 2130903109;
			
			// aapt resource value: 0x7f030010
			public const int btnSavetoSD = 2130903056;
			
			// aapt resource value: 0x7f0300bf
			public const int btnSendAsFile = 2130903231;
			
			// aapt resource value: 0x7f0300be
			public const int btnSendAsText = 2130903230;
			
			// aapt resource value: 0x7f03009b
			public const int cancel = 2130903195;
			
			// aapt resource value: 0x7f03003e
			public const int clearSearchHistory = 2130903102;
			
			// aapt resource value: 0x7f03003d
			public const int clearSearchHistoryTitle = 2130903101;
			
			// aapt resource value: 0x7f03009a
			public const int close = 2130903194;
			
			// aapt resource value: 0x7f0300a9
			public const int contextRevert = 2130903209;
			
			// aapt resource value: 0x7f030098
			public const int copy = 2130903192;
			
			// aapt resource value: 0x7f030046
			public const int createShortcut = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int delete = 2130903111;
			
			// aapt resource value: 0x7f03007d
			public const int deleteAllNotes = 2130903165;
			
			// aapt resource value: 0x7f03007c
			public const int deleteAllNotesTitle = 2130903164;
			
			// aapt resource value: 0x7f03007f
			public const int deleteRemoteNotes = 2130903167;
			
			// aapt resource value: 0x7f03007e
			public const int deleteRemoteNotesTitle = 2130903166;
			
			// aapt resource value: 0x7f03004c
			public const int delete_all = 2130903116;
			
			// aapt resource value: 0x7f03004d
			public const int delete_all_message = 2130903117;
			
			// aapt resource value: 0x7f030049
			public const int delete_message = 2130903113;
			
			// aapt resource value: 0x7f030048
			public const int delete_note = 2130903112;
			
			// aapt resource value: 0x7f030090
			public const int delete_remote = 2130903184;
			
			// aapt resource value: 0x7f03004e
			public const int delete_remote_notes = 2130903118;
			
			// aapt resource value: 0x7f03004f
			public const int delete_remote_notes_message = 2130903119;
			
			// aapt resource value: 0x7f030097
			public const int deleted = 2130903191;
			
			// aapt resource value: 0x7f03003f
			public const int deletedSearchHistory = 2130903103;
			
			// aapt resource value: 0x7f030093
			public const int diff_content = 2130903187;
			
			// aapt resource value: 0x7f030091
			public const int diff_label = 2130903185;
			
			// aapt resource value: 0x7f030092
			public const int diff_titles = 2130903186;
			
			// aapt resource value: 0x7f030056
			public const int discard = 2130903126;
			
			// aapt resource value: 0x7f030054
			public const int edit = 2130903124;
			
			// aapt resource value: 0x7f0300a8
			public const int editTags = 2130903208;
			
			// aapt resource value: 0x7f0300ab
			public const int edit_tags = 2130903211;
			
			// aapt resource value: 0x7f03006e
			public const int edit_title = 2130903150;
			
			// aapt resource value: 0x7f030024
			public const int error = 2130903076;
			
			// aapt resource value: 0x7f0300c2
			public const int firstNoteTitle = 2130903234;
			
			// aapt resource value: 0x7f030087
			public const int gettings_notes = 2130903175;
			
			// aapt resource value: 0x7f03006b
			public const int gt = 2130903147;
			
			// aapt resource value: 0x7f03005c
			public const int highlight = 2130903132;
			
			// aapt resource value: 0x7f030068
			public const int huge = 2130903144;
			
			// aapt resource value: 0x7f030080
			public const int illegalTextSize = 2130903168;
			
			// aapt resource value: 0x7f030059
			public const int italic = 2130903129;
			
			// aapt resource value: 0x7f030067
			public const int large = 2130903143;
			
			// aapt resource value: 0x7f030094
			public const int line_x = 2130903188;
			
			// aapt resource value: 0x7f030095
			public const int local_label = 2130903189;
			
			// aapt resource value: 0x7f03006c
			public const int lt = 2130903148;
			
			// aapt resource value: 0x7f0300c4
			public const int market_description = 2130903236;
			
			// aapt resource value: 0x7f0300c5
			public const int market_promotext = 2130903237;
			
			// aapt resource value: 0x7f0300c6
			public const int market_recent_changes = 2130903238;
			
			// aapt resource value: 0x7f0300c3
			public const int market_title = 2130903235;
			
			// aapt resource value: 0x7f030007
			public const int menuAbout = 2130903047;
			
			// aapt resource value: 0x7f030032
			public const int menuFilterNotebook = 2130903090;
			
			// aapt resource value: 0x7f0300ad
			public const int menuImport = 2130903213;
			
			// aapt resource value: 0x7f030050
			public const int menuNew = 2130903120;
			
			// aapt resource value: 0x7f030006
			public const int menuPrefs = 2130903046;
			
			// aapt resource value: 0x7f0300ae
			public const int menuRevert = 2130903214;
			
			// aapt resource value: 0x7f03003b
			public const int menuSearch = 2130903099;
			
			// aapt resource value: 0x7f03002a
			public const int menuSort = 2130903082;
			
			// aapt resource value: 0x7f030005
			public const int menuSync = 2130903045;
			
			// aapt resource value: 0x7f03009c
			public const int messageAuthComplete = 2130903196;
			
			// aapt resource value: 0x7f03009d
			public const int messageAuthFailed = 2130903197;
			
			// aapt resource value: 0x7f030028
			public const int messageCouldNotSave = 2130903080;
			
			// aapt resource value: 0x7f0300bb
			public const int messageDatabaseReset = 2130903227;
			
			// aapt resource value: 0x7f030069
			public const int messageDiscardChanges = 2130903145;
			
			// aapt resource value: 0x7f030027
			public const int messageErrorNoteParsing = 2130903079;
			
			// aapt resource value: 0x7f030061
			public const int messageErrorParsingXML = 2130903137;
			
			// aapt resource value: 0x7f030029
			public const int messageNoSDCard = 2130903081;
			
			// aapt resource value: 0x7f030063
			public const int messageNoteDeleted = 2130903139;
			
			// aapt resource value: 0x7f030026
			public const int messageNoteNotFound = 2130903078;
			
			// aapt resource value: 0x7f030062
			public const int messageNoteSaved = 2130903138;
			
			// aapt resource value: 0x7f0300b9
			public const int messageNotesBackedUp = 2130903225;
			
			// aapt resource value: 0x7f0300ba
			public const int messageNotesRestored = 2130903226;
			
			// aapt resource value: 0x7f0300a6
			public const int messageRemoteNotesDeleted = 2130903206;
			
			// aapt resource value: 0x7f030064
			public const int messageSelectSize = 2130903140;
			
			// aapt resource value: 0x7f030022
			public const int messageSyncAlreadyInProgress = 2130903074;
			
			// aapt resource value: 0x7f0300a7
			public const int messageSyncCancelled = 2130903207;
			
			// aapt resource value: 0x7f03001f
			public const int messageSyncComplete = 2130903071;
			
			// aapt resource value: 0x7f0300a5
			public const int messageSyncConnectingFailed = 2130903205;
			
			// aapt resource value: 0x7f030023
			public const int messageSyncError = 2130903075;
			
			// aapt resource value: 0x7f030021
			public const int messageSyncNoConnection = 2130903073;
			
			// aapt resource value: 0x7f030020
			public const int messageSyncNoNote = 2130903072;
			
			// aapt resource value: 0x7f0300a1
			public const int messageSyncNoteDeleteError = 2130903201;
			
			// aapt resource value: 0x7f03009e
			public const int messageSyncNoteDeleted = 2130903198;
			
			// aapt resource value: 0x7f0300a3
			public const int messageSyncNotePullError = 2130903203;
			
			// aapt resource value: 0x7f0300a0
			public const int messageSyncNotePulled = 2130903200;
			
			// aapt resource value: 0x7f0300a2
			public const int messageSyncNotePushError = 2130903202;
			
			// aapt resource value: 0x7f03009f
			public const int messageSyncNotePushed = 2130903199;
			
			// aapt resource value: 0x7f0300a4
			public const int messageSyncParseFailed = 2130903204;
			
			// aapt resource value: 0x7f03005b
			public const int mono = 2130903131;
			
			// aapt resource value: 0x7f03004b
			public const int no = 2130903115;
			
			// aapt resource value: 0x7f030066
			public const int normal = 2130903142;
			
			// aapt resource value: 0x7f030036
			public const int noteOptions = 2130903094;
			
			// aapt resource value: 0x7f0300aa
			public const int note_x_tags = 2130903210;
			
			// aapt resource value: 0x7f030099
			public const int old = 2130903193;
			
			// aapt resource value: 0x7f03008f
			public const int overwrite_local = 2130903183;
			
			// aapt resource value: 0x7f03008e
			public const int overwrite_remote = 2130903182;
			
			// aapt resource value: 0x7f030016
			public const int prefAuthenticate = 2130903062;
			
			// aapt resource value: 0x7f030077
			public const int prefAutoSave = 2130903159;
			
			// aapt resource value: 0x7f030076
			public const int prefAutoSaveTitle = 2130903158;
			
			// aapt resource value: 0x7f030073
			public const int prefBaseSize = 2130903155;
			
			// aapt resource value: 0x7f03002c
			public const int prefDefaultSorting = 2130903084;
			
			// aapt resource value: 0x7f030079
			public const int prefDeletedNotes = 2130903161;
			
			// aapt resource value: 0x7f030078
			public const int prefDeletedNotesTitle = 2130903160;
			
			// aapt resource value: 0x7f030072
			public const int prefDisplay = 2130903154;
			
			// aapt resource value: 0x7f030018
			public const int prefFolderCreated = 2130903064;
			
			// aapt resource value: 0x7f030017
			public const int prefLocation = 2130903063;
			
			// aapt resource value: 0x7f03001a
			public const int prefNoValidEntry = 2130903066;
			
			// aapt resource value: 0x7f030019
			public const int prefNoValidLocation = 2130903065;
			
			// aapt resource value: 0x7f03007b
			public const int prefNoteTemplates = 2130903163;
			
			// aapt resource value: 0x7f03007a
			public const int prefNoteTemplatesTitle = 2130903162;
			
			// aapt resource value: 0x7f030014
			public const int prefSDCard = 2130903060;
			
			// aapt resource value: 0x7f03001d
			public const int prefServerEmpty = 2130903069;
			
			// aapt resource value: 0x7f03002e
			public const int prefSortDate = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int prefSortTitle = 2130903087;
			
			// aapt resource value: 0x7f03002d
			public const int prefSorting = 2130903085;
			
			// aapt resource value: 0x7f030074
			public const int prefSync = 2130903156;
			
			// aapt resource value: 0x7f03001b
			public const int prefSyncCompleteAuth = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int prefSyncConnectionFailed = 2130903068;
			
			// aapt resource value: 0x7f030013
			public const int prefSyncServer = 2130903059;
			
			// aapt resource value: 0x7f030012
			public const int prefSyncService = 2130903058;
			
			// aapt resource value: 0x7f030015
			public const int prefTomboyWeb = 2130903061;
			
			// aapt resource value: 0x7f030075
			public const int prefTools = 2130903157;
			
			// aapt resource value: 0x7f030071
			public const int pref_title = 2130903153;
			
			// aapt resource value: 0x7f030096
			public const int remote_label = 2130903190;
			
			// aapt resource value: 0x7f0300b6
			public const int restorePref = 2130903222;
			
			// aapt resource value: 0x7f0300b5
			public const int restorePrefTitle = 2130903221;
			
			// aapt resource value: 0x7f0300b8
			public const int restore_notes = 2130903224;
			
			// aapt resource value: 0x7f0300b7
			public const int restore_notes_title = 2130903223;
			
			// aapt resource value: 0x7f0300b1
			public const int revert_note = 2130903217;
			
			// aapt resource value: 0x7f0300b2
			public const int revert_note_message = 2130903218;
			
			// aapt resource value: 0x7f0300af
			public const int revert_notes = 2130903215;
			
			// aapt resource value: 0x7f0300b0
			public const int revert_notes_message = 2130903216;
			
			// aapt resource value: 0x7f030055
			public const int save = 2130903125;
			
			// aapt resource value: 0x7f030039
			public const int search_description = 2130903097;
			
			// aapt resource value: 0x7f030038
			public const int search_hint = 2130903096;
			
			// aapt resource value: 0x7f03006f
			public const int search_title = 2130903151;
			
			// aapt resource value: 0x7f030037
			public const int send = 2130903095;
			
			// aapt resource value: 0x7f0300bd
			public const int sendChoice = 2130903229;
			
			// aapt resource value: 0x7f0300bc
			public const int sendChoiceTitle = 2130903228;
			
			// aapt resource value: 0x7f030044
			public const int shortcut_menu_item_caption = 2130903108;
			
			// aapt resource value: 0x7f030070
			public const int shortcut_title = 2130903152;
			
			// aapt resource value: 0x7f030043
			public const int shortcuts_view_caption = 2130903107;
			
			// aapt resource value: 0x7f03005d
			public const int size = 2130903133;
			
			// aapt resource value: 0x7f030065
			public const int small = 2130903141;
			
			// aapt resource value: 0x7f030030
			public const int sortByDate = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int sortByTitle = 2130903089;
			
			// aapt resource value: 0x7f03000b
			public const int strAbout = 2130903051;
			
			// aapt resource value: 0x7f030033
			public const int strListEmptyNoNotebooks = 2130903091;
			
			// aapt resource value: 0x7f030004
			public const int strListEmptyNoNotes = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int strListEmptyWaiting = 2130903043;
			
			// aapt resource value: 0x7f03003a
			public const int strNoResults = 2130903098;
			
			// aapt resource value: 0x7f030011
			public const int strWait = 2130903057;
			
			// aapt resource value: 0x7f03000a
			public const int strWelcome = 2130903050;
			
			// aapt resource value: 0x7f03005a
			public const int strike = 2130903130;
			
			// aapt resource value: 0x7f03008c
			public const int sync_conflict_deleted = 2130903180;
			
			// aapt resource value: 0x7f0300c0
			public const int sync_conflict_import_message = 2130903232;
			
			// aapt resource value: 0x7f03008b
			public const int sync_conflict_message = 2130903179;
			
			// aapt resource value: 0x7f03008a
			public const int sync_conflict_title = 2130903178;
			
			// aapt resource value: 0x7f03008d
			public const int sync_conflict_titles_message = 2130903181;
			
			// aapt resource value: 0x7f030085
			public const int syncing = 2130903173;
			
			// aapt resource value: 0x7f030086
			public const int syncing_connect = 2130903174;
			
			// aapt resource value: 0x7f030088
			public const int syncing_local = 2130903176;
			
			// aapt resource value: 0x7f030089
			public const int syncing_remote = 2130903177;
			
			// aapt resource value: 0x7f03005f
			public const int text = 2130903135;
			
			// aapt resource value: 0x7f030040
			public const int textModified = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int textToday = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int textYexterday = 2130903106;
			
			// aapt resource value: 0x7f030009
			public const int titleAbout = 2130903049;
			
			// aapt resource value: 0x7f03002b
			public const int titleDefaultSorting = 2130903083;
			
			// aapt resource value: 0x7f03006a
			public const int titleDiscardChanges = 2130903146;
			
			// aapt resource value: 0x7f030060
			public const int titleErrorParsingXML = 2130903136;
			
			// aapt resource value: 0x7f030025
			public const int titleNoteNotFound = 2130903077;
			
			// aapt resource value: 0x7f03001e
			public const int titleSyncService = 2130903070;
			
			// aapt resource value: 0x7f030008
			public const int titleWelcome = 2130903048;
			
			// aapt resource value: 0x7f0300ac
			public const int undelete = 2130903212;
			
			// aapt resource value: 0x7f030035
			public const int view = 2130903093;
			
			// aapt resource value: 0x7f03006d
			public const int view_title = 2130903149;
			
			// aapt resource value: 0x7f03005e
			public const int xml = 2130903134;
			
			// aapt resource value: 0x7f03004a
			public const int yes = 2130903114;
			
			private String()
			{
			}
		}
	}
}
